list: $/bishopm/examening/models/resource/columns.yaml
modelClass: Bishopm\Examening\Models\Resource
title: Resources
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'bishopm/examening/resources/update/:id'
